import{S as L,a as y,i as d}from"./assets/vendor-Dr0KmOfh.js";(function(){const i=document.createElement("link").relList;if(i&&i.supports&&i.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const n of t)if(n.type==="childList")for(const s of n.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&a(s)}).observe(document,{childList:!0,subtree:!0});function r(t){const n={};return t.integrity&&(n.integrity=t.integrity),t.referrerPolicy&&(n.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?n.credentials="include":t.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function a(t){if(t.ep)return;t.ep=!0;const n=r(t);fetch(t.href,n)}})();let w=new L(".gallery a",{captionsData:"alt",captionDelay:250,animationSpeed:200,fadeSpeed:200});function E(e){const i=document.querySelector(".gallery");if(!i){console.error("Gallery container not found!");return}const r=e.map(a=>`
      <li class="gallery-item">
        <a href="${a.largeImageURL}">
          <img
            src="${a.webformatURL}"
            alt="${a.tags}"
            loading="lazy"
          />
        </a>
        <div class="info">
          <p><b>Likes:</b> ${a.likes}</p>
          <p><b>Views:</b> ${a.views}</p>
          <p><b>Comments:</b> ${a.comments}</p>
          <p><b>Downloads:</b> ${a.downloads}</p>
        </div>
      </li>
    `).join("");i.insertAdjacentHTML("beforeend",r),w.refresh()}function A(){const e=document.querySelector(".gallery");e&&(e.innerHTML="")}function S(){var e;(e=document.querySelector(".loader"))==null||e.classList.remove("hidden")}function P(){var e;(e=document.querySelector(".loader"))==null||e.classList.add("hidden")}const v="52507179-0a3bafb5b272d1890f0df5cc7",R="https://pixabay.com/api/",C=15,q=y.create({baseURL:R,params:{key:v,image_type:"photo",orientation:"horizontal",safesearch:!0}});async function H(e,i=1,r=C,a){var t,n;try{if(!e||typeof e!="string"||e.trim()==="")return{hits:[],totalHits:0};const{data:s}=await q.get("",{params:{q:e,page:i,per_page:r},signal:a}),g=Array.isArray(s==null?void 0:s.hits)?s.hits:[],b=Number.isFinite(s==null?void 0:s.totalHits)?s.totalHits:0;return{hits:g,totalHits:b}}catch(s){throw(n=(t=y).isCancel)!=null&&n.call(t,s)||console.error("Pixabay API error:",(s==null?void 0:s.message)||s),s}}const u=document.querySelector(".form"),o=document.querySelector(".load-more");let h="",c=1,f=0;const m=15;let l=null;function I(e,i,r){const a=Math.ceil((e||0)/r);i<a?o==null||o.classList.remove("hidden"):o==null||o.classList.add("hidden")}function $(){d.show({message:"Sorry, there are no images matching your search query.<br>Please try again!",position:"topRight",timeout:4e3,close:!0,progressBar:!1,backgroundColor:"#f44336",messageColor:"#fff",layout:2,maxWidth:420,class:"custom-toast",icon:"fa fa-times-circle"})}function x(){d.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight",timeout:4e3})}async function p({doScroll:e=!1}={}){var i;l&&l.abort(),l=new AbortController;try{S();const r=await H(h,c,m,l.signal);if(!r.hits||r.hits.length===0){c===1&&$(),o==null||o.classList.add("hidden");return}E(r.hits),f=r.totalHits||0;const a=Math.ceil(f/m);if(I(f,c,m),c>=a&&x(),e){const t=document.querySelector(".gallery-item");if(t){const{height:n}=t.getBoundingClientRect();window.scrollBy({top:n*2,behavior:"smooth"})}}}catch(r){if((r==null?void 0:r.name)==="CanceledError"||(r==null?void 0:r.code)==="ERR_CANCELED")return;d.error({title:"Error",message:"Failed to fetch images. Try later!"}),console.error("API Error:",r)}finally{P(),(i=u.querySelector("button[type='submit']"))==null||i.removeAttribute("disabled"),o==null||o.removeAttribute("disabled")}}u.addEventListener("submit",async e=>{var i;if(e.preventDefault(),h=u.elements["search-text"].value.trim(),c=1,A(),o==null||o.classList.add("hidden"),!h){d.error({title:"Error",message:"Enter a search term!"});return}(i=u.querySelector("button[type='submit']"))==null||i.setAttribute("disabled","true"),await p()});o==null||o.addEventListener("click",async()=>{c+=1,o.setAttribute("disabled","true"),await p({doScroll:!0})});
//# sourceMappingURL=index.js.map
