import{S as g,a as m,i as l}from"./assets/vendor-Dr0KmOfh.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const a of t)if(a.type==="childList")for(const r of a.addedNodes)r.tagName==="LINK"&&r.rel==="modulepreload"&&s(r)}).observe(document,{childList:!0,subtree:!0});function i(t){const a={};return t.integrity&&(a.integrity=t.integrity),t.referrerPolicy&&(a.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?a.credentials="include":t.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function s(t){if(t.ep)return;t.ep=!0;const a=i(t);fetch(t.href,a)}})();let b=new g(".gallery a",{captionsData:"alt",captionDelay:250,animationSpeed:200,fadeSpeed:200});function L(e){const o=document.querySelector(".gallery");if(!o){console.error("Gallery container not found!");return}const i=e.map(s=>`
      <li class="gallery-item">
        <a href="${s.largeImageURL}">
          <img
            src="${s.webformatURL}"
            alt="${s.tags}"
            loading="lazy"
          />
        </a>
        <div class="info">
          <p><b>Likes:</b> ${s.likes}</p>
          <p><b>Views:</b> ${s.views}</p>
          <p><b>Comments:</b> ${s.comments}</p>
          <p><b>Downloads:</b> ${s.downloads}</p>
        </div>
      </li>
    `).join("");o.insertAdjacentHTML("beforeend",i),b.refresh()}function w(){const e=document.querySelector(".gallery");e&&(e.innerHTML="")}function P(){var e;(e=document.querySelector(".loader"))==null||e.classList.remove("hidden")}function S(){var e;(e=document.querySelector(".loader"))==null||e.classList.add("hidden")}const v="52507179-0a3bafb5b272d1890f0df5cc7",E="https://pixabay.com/api/",A=15,H=m.create({baseURL:E,params:{key:v,image_type:"photo",orientation:"horizontal",safesearch:!0}});async function R(e,o=1,i=A,s){var t,a;try{if(!e||typeof e!="string"||e.trim()==="")return{hits:[],totalHits:0};const{data:r}=await H.get("",{params:{q:e,page:o,per_page:i},signal:s}),y=Array.isArray(r==null?void 0:r.hits)?r.hits:[],p=Number.isFinite(r==null?void 0:r.totalHits)?r.totalHits:0;return{hits:y,totalHits:p}}catch(r){throw(a=(t=m).isCancel)!=null&&a.call(t,r)||console.error("Pixabay API error:",(r==null?void 0:r.message)||r),r}}const u=document.querySelector(".form"),n=document.querySelector(".load-more");let d="",c=1,f=0;const I=15;u.addEventListener("submit",async e=>{if(e.preventDefault(),d=u.elements["search-text"].value.trim(),c=1,w(),n.classList.add("hidden"),!d){l.error({title:"Error",message:"Enter a search term!"});return}await h()});n.addEventListener("click",async()=>{c+=1,await h(!0)});async function h(e=!1){try{P();const o=await R(d,c);if(!o.hits||o.hits.length===0){c===1&&l.show({message:"Sorry, there are no images matching your search query.<br>Please try again!",position:"topRight",timeout:4e3,close:!0,progressBar:!1,backgroundColor:"#f44336",messageColor:"#fff",layout:2,maxWidth:420,class:"custom-toast",icon:"fa fa-times-circle"}),n.classList.add("hidden");return}L(o.hits),f=o.totalHits;const i=Math.ceil(f/I);if(c<i?n.classList.remove("hidden"):(n.classList.add("hidden"),l.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight",timeout:4e3})),e){const s=document.querySelector(".gallery-item");if(s){const{height:t}=s.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}}}catch(o){l.error({title:"Error",message:"Failed to fetch images. Try later!"}),console.error("API Error:",o)}finally{S()}}
//# sourceMappingURL=index.js.map
